events {
    worker_connections 1024
}
http {
    upstream nextcloud_cluster {
        ip_hash;
        server app1:80;
        server app2:80;
        server app3:80;
    }

    server {
        listen 80;
        server_name 10.0.0.1;

        location / {
            proxy_pass http://nextcloud_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            add_header X-Backend-Server $upstream_addr;
        }
    }
}